let items=[];let dragIndex=null;
const slots=document.getElementById('slots'),controls=document.getElementById('controls'),canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d'),statusEl=document.getElementById('status'),imgOut=document.getElementById('imgOut');
function load(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file);const img=new Image();img.onload=()=>resolve({img,url,name:file.name,x:0,y:0,zoom:1.15,flip:false});img.onerror=reject;img.src=url;});}
document.getElementById('files').addEventListener('change',async e=>{const files=Array.from(e.target.files).filter(f=>f.type.startsWith('image/')).slice(0,5);items=[];statusEl.textContent='読み込み中…';for(const f of files){items.push(await load(f));}renderAll();statusEl.textContent=items.length+'枚読み込みました';});
function renderSlots(){slots.innerHTML='';const max=Math.max(items.length,5);for(let i=0;i<max;i++){const d=document.createElement('div');d.className='slot';d.draggable=!!items[i];d.dataset.index=i;if(items[i]){d.innerHTML='<span class="badge">'+(i+1)+'</span><img src="'+items[i].url+'">';d.addEventListener('dragstart',()=>{dragIndex=i;d.classList.add('dragging');});d.addEventListener('dragend',()=>{dragIndex=null;d.classList.remove('dragging');});d.addEventListener('dragover',ev=>ev.preventDefault());d.addEventListener('drop',ev=>{ev.preventDefault();const to=Number(d.dataset.index);if(dragIndex===null||dragIndex===to)return;const moved=items.splice(dragIndex,1)[0];items.splice(to,0,moved);renderAll();});}else{d.innerHTML='<span class="badge">'+(i+1)+'</span>画像';}slots.appendChild(d);}}
function renderControls(){controls.innerHTML='';items.forEach((it,i)=>{const box=document.createElement('div');box.className='itemCtl';box.innerHTML=`<div class="itemTop"><strong>画像${i+1}</strong><div class="miniBtns"><button class="ghost" data-act="left">←</button><button class="ghost" data-act="right">→</button><button class="ghost" data-act="up">↑</button><button class="ghost" data-act="down">↓</button><button class="ghost" data-act="flip">${it.flip?'反転中':'左右反転'}</button></div></div><div class="sliderRow"><span>左右</span><input type="range" min="-120" max="120" value="${it.x}" data-kind="x"><span>${it.x}</span></div><div class="sliderRow"><span>上下</span><input type="range" min="-120" max="120" value="${it.y}" data-kind="y"><span>${it.y}</span></div><div class="sliderRow"><span>拡大</span><input type="range" min="90" max="170" value="${Math.round(it.zoom*100)}" data-kind="zoom"><span>${Math.round(it.zoom*100)}%</span></div>`;
box.querySelectorAll('button').forEach(btn=>{btn.addEventListener('click',()=>{const act=btn.dataset.act;if(act==='left')it.x-=10;if(act==='right')it.x+=10;if(act==='up')it.y-=10;if(act==='down')it.y+=10;if(act==='flip')it.flip=!it.flip;it.x=Math.max(-120,Math.min(120,it.x));it.y=Math.max(-120,Math.min(120,it.y));renderAll();});});
box.querySelectorAll('input[type=range]').forEach(sl=>{sl.addEventListener('input',()=>{if(sl.dataset.kind==='x')it.x=Number(sl.value);if(sl.dataset.kind==='y')it.y=Number(sl.value);if(sl.dataset.kind==='zoom')it.zoom=Number(sl.value)/100;renderAll(false);});});controls.appendChild(box);});}
function fontCss(){const v=document.getElementById('fontFamily').value;if(v==='mincho')return '"Yu Mincho","Hiragino Mincho ProN","Times New Roman",serif';if(v==='gothic')return '"Hiragino Sans","Yu Gothic",Arial,sans-serif';if(v==='didot')return 'Didot,"Bodoni 72","Times New Roman",serif';if(v==='bodoni')return '"Bodoni 72","Bodoni 72 Smallcaps","Times New Roman",serif';if(v==='script')return '"Snell Roundhand","Zapfino","Brush Script MT",cursive';return 'Georgia,"Times New Roman",serif';}
function coverParams(item,w,h){const img=item.img,iw=img.naturalWidth,ih=img.naturalHeight,scale=Math.max(w/iw,h/ih)*item.zoom,sw=w/scale,sh=h/scale;let sx=(iw-sw)/2+item.x/scale,sy=(ih-sh)*0.36+item.y/scale;sx=Math.max(0,Math.min(iw-sw,sx));sy=Math.max(0,Math.min(ih-sh,sy));return{sx,sy,sw,sh};}
function drawItem(item,x,y,w,h){const p=coverParams(item,w,h);ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();if(item.flip){ctx.translate(x+w,y);ctx.scale(-1,1);ctx.drawImage(item.img,p.sx,p.sy,p.sw,p.sh,0,0,w,h);}else{ctx.drawImage(item.img,p.sx,p.sy,p.sw,p.sh,x,y,w,h);}ctx.restore();}
function drawFeather(item,x,y,w,h,side,fade){if(fade<=0)return;const p=coverParams(item,w,h),off=document.createElement('canvas');off.width=Math.ceil(w);off.height=Math.ceil(h);const octx=off.getContext('2d');octx.save();if(item.flip){octx.translate(w,0);octx.scale(-1,1);octx.drawImage(item.img,p.sx,p.sy,p.sw,p.sh,0,0,w,h);}else{octx.drawImage(item.img,p.sx,p.sy,p.sw,p.sh,0,0,w,h);}octx.restore();octx.globalCompositeOperation='destination-in';const grad=octx.createLinearGradient(0,0,w,0);if(side==='left'){grad.addColorStop(0,'rgba(0,0,0,0)');grad.addColorStop(Math.min(1,fade/w),'rgba(0,0,0,1)');grad.addColorStop(1,'rgba(0,0,0,1)');}else{grad.addColorStop(0,'rgba(0,0,0,1)');grad.addColorStop(Math.max(0,1-fade/w),'rgba(0,0,0,1)');grad.addColorStop(1,'rgba(0,0,0,0)');}octx.fillStyle=grad;octx.fillRect(0,0,w,h);ctx.drawImage(off,x,y);}
function draw(){ctx.clearRect(0,0,750,250);ctx.fillStyle='#eee';ctx.fillRect(0,0,750,250);const n=items.length;if(!n){ctx.fillStyle='#aaa';ctx.font='20px sans-serif';ctx.textAlign='center';ctx.fillText('画像を4〜5枚選択してください',375,125);return;}const seamless=document.getElementById('seamlessOn').checked,overlap=seamless?Number(document.getElementById('overlap').value||0):0,fade=seamless?Number(document.getElementById('fadeWidth').value||0):0,baseW=seamless?(750+overlap*(n-1))/n:750/n;if(!seamless){const w=750/n;for(let i=0;i<n;i++)drawItem(items[i],i*w,0,w,250);}else{for(let i=0;i<n;i++){const x=i*(baseW-overlap);drawItem(items[i],x,0,baseW,250);}for(let i=1;i<n;i++){const seamX=i*(baseW-overlap),leftX=(i-1)*(baseW-overlap),rightX=i*(baseW-overlap);drawFeather(items[i-1],leftX,0,baseW,250,'right',fade);drawFeather(items[i],rightX,0,baseW,250,'left',fade);const gx=seamX-fade/2,g=ctx.createLinearGradient(gx,0,gx+fade,0);g.addColorStop(0,'rgba(255,255,255,0)');g.addColorStop(.5,'rgba(255,255,255,.10)');g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.fillRect(gx,0,fade,250);}}const pos=document.getElementById('textPos').value,text=document.getElementById('shop').value.trim();if(pos!=='none'&&text){const fs=parseInt(document.getElementById('fontSize').value||'34',10),y=pos==='top'?48:pos==='center'?125:208;ctx.save();ctx.font=fs+'px '+fontCss();ctx.textAlign='center';ctx.textBaseline='middle';if(document.getElementById('shadowOn').checked){ctx.shadowColor='rgba(0,0,0,.45)';ctx.shadowBlur=7;ctx.shadowOffsetY=2;}ctx.fillStyle=document.getElementById('textColor').value;ctx.fillText(text,375,y);ctx.restore();}}
function renderAll(rebuild=true){renderSlots();if(rebuild)renderControls();draw();}
function save(){draw();const data=canvas.toDataURL('image/png'),a=document.createElement('a');a.download='salon-banner-studio-750x250.png';a.href=data;a.click();imgOut.innerHTML='<p class="note">保存できない場合は下の画像を長押し保存してください。</p><img src="'+data+'">';}
document.getElementById('save').addEventListener('click',save);
['shop','fontFamily','textColor','fontSize','textPos','shadowOn','seamlessOn','overlap','fadeWidth'].forEach(id=>{const el=document.getElementById(id);el.addEventListener('input',()=>renderAll(false));el.addEventListener('change',()=>renderAll(false));});
document.querySelectorAll('.swatch').forEach(b=>{b.addEventListener('click',()=>{document.getElementById('textColor').value=b.dataset.color;renderAll(false);});});renderAll();